# Generated by Django 4.1.7 on 2023-04-07 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
